# Lenguaje de programación
language: python

# Versiones de python
python:

    - "3.6.9"
    - "3.7.0"
    - "3.7.3"
    - "3.7.5"
    - "3.8.0"

#Servcios utilizados
services:
    - mongodb

#Instalar todo lo necesario
before_install:
    - pip install -r requirements.txt

#Ejecución de test unitarios y de covertura
script:
    - invoke test
    - invoke coverage

#Pasa los resultados a codecov
after_success:
    - codecov
